### ISSUE TITLE
deepin15.5 联想（Lenovo） 小新潮5000 无法安装

### ISSUE THREAD

**Issue by tsuibin** [linuxdeepin/deepin-installer-reborn#4]
U盘方式安装
1 deepin15.5 联想（Lenovo） 小新潮5000 无法安装
2 该U盘在其他笔记本和PC机上安装系统OK

**Comment by BLumia** [comment]
感谢汇报问题，抱歉我们今年早些时候才开始额外留意 GitHub 的 Issue ，现在 Deepin 的最新版是 15.10 ，可以尝试安装 15.10 然后看看是否依然有问题。如果有的话，可以在 [Developer Center](https://github.com/linuxdeepin/developer-center) 开新 Issue 描述问题。
