### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Firesuiry** [linuxdeepin/deepin-installer-reborn#5]
1.win7安装最后显示需要关闭windows快速启动，但是实际上并不需要关闭直接重启就行，建议修改描述
2.重启显示无法找到gdldr文件，我把wubildr 和wubildr.mbr复制到每个磁盘根目录以后可以进入系统了。

**Comment by BLumia** [comment]
感谢反馈，抱歉之前并没有太多留意 GitHub ，于前段时间我们已经把部分工作流程转移到 GitHub 了。

您可以尝试一下 15.10 是否依然有上述问题，如果有的话可以在 [Developer Center](https://github.com/linuxdeepin/developer-center) 汇报问题，谢谢。
